swagger: "2.0"
info:
  description: Shown below is the swagger config file to scaffold our API for Lander Labs
  version: "0.0.1"
  title: Lander Labs API config
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /events:
    get:
      operationId: "events.read"
      tags:
        - "Events"
      summary: "The events data structure for Lander labs"
      description: "Read the list of events"
      responses:
        200:
          description: "Successful read of all events list operation"
          schema:
            type: "array"
            items:
              properties:
                title:
                  type: "string"
                start_date:
                  type: "string"